name: Rebuild Docs

on:
  push:
    tags:
      - '@cipherstash/stack@*'
      - '@cipherstash/drizzle@*'

jobs:
  trigger-docs-rebuild:
    name: Trigger Docs Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        env:
          WEBHOOK_URL: ${{ secrets.DOCS_WEBHOOK_URL }}
        run: |
          curl -X POST "$WEBHOOK_URL"
